### ISSUE TITLE
Get de Session ID

### ISSUE THREAD

**Issue by rtcarbone** [zoom/videosdk-ui-toolkit-web#6]
Hello! Is there any way to retrieve de session id through the ui toolkit?

**Comment by tommygaessler** [comment]
Hey @rtcarbone , yes, we do provide the Session ID in the user interface on the settings popup.

You can also retrieve the Session ID via our REST APIs since you are setting the Session Name (see the query params): https://developers.zoom.us/docs/video-sdk/apis/#operation/sessions

Are you looking to retrieve the Session ID programmatically on the client side?

**Comment by rtcarbone** [comment]
Nice, I didn't notice that possibility. Yeah, I need it for cloud recording. Is there another way to start the recording? Maybe configure automatic recording everytime a session is started?

**Comment by tommygaessler** [comment]
Hey @rtcarbone ,

You can start cloud recording programmatically with the [REST API](https://developers.zoom.us/docs/video-sdk/apis/#operation/inSessionEventsControl), or, in a future release we will have a Cloud Recording button in the user interface.

Are you also interested in starting recording programmatically from the client side?

**Comment by rtcarbone** [comment]
That's great news @tommygaessler! You helped me a lot, I couldn't thank you enough. That´s all for now. I saw the documentation and learned how to do the call from the client side. One last wish: an interesting feature in the toolkit would be the possibility of selecting the language so the messages that are displayed in toasts could be translated.

**Comment by tommygaessler** [comment]
Happy to help @rtcarbone , glad you are all set, please reach out if you need anything else!

For the language selection, that is a great feature request, we will evaluate that.
